### ISSUE TITLE
list_units function is private

### ISSUE THREAD

**Issue by rgwood** [gwbres/systemctl#1]
Hi, thanks for making this library! I think it's really useful to have a simple Rust library for working with systemd.

I tried following the "Service enumeration" example in the README, but it fails because `list_units()` is not public:
```
error[E0603]: function `list_units` is private
  --> src/main.rs:6:28
   |
6  |     let units = systemctl::list_units(None, None);
   |                            ^^^^^^^^^^ private function
```

**Comment by gwbres** [comment]
hello @rgwood 

sorry for the delayed response.
Indeed, I ran into the same "problem", I just pushed a new release.

**Comment by gwbres** [comment]
> Hello, it's still private, the source code says the same. https://github.com/gwbres/systemctl/blob/main/src/lib.rs#L96

Hello @beckend 
indeed, probably made a mistake here, I just fixed that
