### ISSUE TITLE
feasibility of not depending on the systemctl 

### ISSUE THREAD

**Issue by blueForestIcarus** [gwbres/systemctl#2]
Ideally, for cases like these, it would be possible to manage systemd through a library instead of systemctl.
A reasonable question is, for the feature-set of this library, what would be involved in implementing the systemctl features in rust?

**Comment by blueForestIcarus** [comment]
Actually, this might be simpler than parsing systemctl terminal output

https://www.freedesktop.org/wiki/Software/systemd/dbus/

**Comment by gwbres** [comment]
Hello @blueForestIcarus 

> Never-mind, this already exists https://github.com/lucab/zbus_systemd

I was not aware of "dbus", that can also be a solution to the issue. With possible benefits of a more stable/standard approach.
I checked it out when you open this thread, other solutions exist too [like this one](https://github.com/diwic/dbus-rs)

**Comment by blueForestIcarus** [comment]
Yes there are 2 major rust crates, [dbus-rs](https://github.com/diwic/dbus-rs) binds to standard libdbus, and [zbus](https://gitlab.freedesktop.org/dbus/zbus) implements a pure rust solution. 
The crate I [linked](https://github.com/lucab/zbus_systemd) auto-generates zbus proxies from the source code to systemd's dbus interface.

I've been using zbus and zbus-systemd for my systemctl alternative [sys](https://github.com/blueForestIcarus/sys) and it is going pretty smoothly.
