### ISSUE TITLE
Comparison with `zbus_systemd`?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [gwbres/systemctl#30]
I wanted to programmatically restart a systemd service, and since I didn't want to set the `SYSTEMCTL_PATH` variable, I used https://github.com/lucab/zbus_systemd instead. The advantage to using the zbus crate is that it is less hacky / unstable because it uses D-Bus instead of the CLI. Can `zbus_systemd` replace all uses of this crate? Are there some scenarios where this crate is still the better choice?

Even if `zbus_systemd` can't replace this crate entirely, it would still be good to mention in the README that `zbus_systemd` might be the better way of controlling systemd with Rust.

After I made this issue I realized that #2 already exists, but nothing was really done with that issue, so I think replacing this crate / mentioning the zbus crate in the README should be reconsidered.

**Comment by gwbres** [comment]
Hello,

> I used https://github.com/lucab/zbus_systemd instead. The advantage to using the zbus crate is that it is less hacky / unstable because it uses D-Bus instead of the CLI

Yes, that is what is stated in the front page. The simple reason this crate exist, is that I did not find `z-bus` or it did not exist at the time I needed to manage a few services. Zbus is the best choice.

> Can zbus_systemd replace all uses of this crate

I think it  can, I'm not aware of scenarios where this crate would be a better choice

>  so I think replacing this crate / mentioning the zbus crate in the README should be reconsidered.

we already have explanations about this in the README I think
